- description: Query from the remote schema returning errors and data
  url: /v1/graphql
  status: 200
  headers:
    x-fake-operation-name: DataAndError
  response:
    data:
    errors:
    - extensions:
        code: validation-failed
        path: "$.selectionSet.test_lol"
      message: 'field ''test'' not found in type: ''query_root'''
  query:
    query: |
      query DataAndError {
        test {
          id
          created_at
        }
      }
